### ISSUE TITLE
Revamp tests

### ISSUE THREAD

**Issue by Kawacrepe** [NodeSecure/authors#13]
Our tests must be refacto, we must execute `temp.js` to create the nsecure-result.json which will be analyzed by the package.

We want to remove this file and include the step in our tests.

The second improvement consist in what Rossbob told me in another PR
____________

I would have added some tests over rewriting it :
- one without any options (flags & domainInformations)
- one with flags
- one with domainInformations

but it may be overkill

_Originally posted by @Rossb0b in https://github.com/NodeSecure/authors/pull/12#pullrequestreview-1066608856_

**Comment by fabnguess** [comment]
@Kawacrepe can I take this issue?

**Comment by Kawacrepe** [comment]
Yes, feel free to ping me if some additionnals informations are needed :)

**Comment by fabnguess** [comment]
@Kawacrepe  Yes, I want to make sure I understood the task correctly. This is effectively removing the temp.js file after carefully transposing its logic into a unit test. In conclusion, should we also implement Rossbob's recommendations

**Comment by Kawacrepe** [comment]
Exactly, we should look at the rossbob recommendations :)

**Comment by fraxken** [comment]
Going to rework them
