### ISSUE TITLE
Author/Maintainer with an expired email

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/authors#8]
Author and Maintainer with an expired email domain are exposed to hackers.

See: [What are Weak Links in the npm Supply Chain?](https://arxiv.org/pdf/2112.10165.pdf)

How could we identify and prevent this with code ? That's the subject of this issue.

**Comment by tony-go** [comment]
Maybe we could create a package like this one: https://www.npmjs.com/package/email-check

**Comment by fraxken** [comment]
@mbalabash I'll tag you if you have any ideas You might be interested in these topics (knowing that they will soon be integrated on Scanner).

**Comment by Kawacrepe** [comment]
Let's go! I'm gonna try to setup a `mail-check` library :)
