### ISSUE TITLE
Inactive Maintainer (or Publisher ?)

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/authors#9]
It would be relevant to know if a maintainer is still active on npm. This would probably only be possible if the person has already published a package.

For example, we could consider that someone who has published in the past but nothing within three years would be considered as not active.

Any help or opinions are welcome.

**Comment by Kawacrepe** [comment]
Based on this [paper](https://arxiv.org/pdf/2112.10165.pdf), I would say we need to distinguish between a maintainer which is no longer active on a package and a maintainer who is no longer active on the entire npm registry.

> Because an inactive
package may have maintainers who are active in other packages,
whereas inactive maintainers indicate the maintainer is inactive in
the entire npm registry

I think 2 years of inactivity is a good default value

**Comment by PierreDemailly** [comment]
I'm on it

**Comment by Rossb0b** [comment]
Pending PR around the subject https://github.com/NodeSecure/github/pull/82

**Comment by PierreDemailly** [comment]
@Rossb0b is on it btw
